### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by calmilamsy**
1. Works on python3 now.
2. Windows python no longer included in the LTS zip, its now downloaded from official source.
3. Cleanup moved to python for easier maintenance.
4. This can now actually work on OSX if you provide the right natives and python version.

!!!AS ALWAYS, TEST THIS BEFORE MERGE!!!

### CODE REVIEW

**Comment by calmilamsy** [comment]
Finally, this branch is ready to be properly tested.

Ive made an entire mod in this branch, but you guys should test it on linux just to be safe.

**Comment by Johnanater** [comment]
Will be testing

**Comment by Dereku** [comment]
0086d677e117ea939f7d48862ae191633601196b It is also better to delete unused files. imo.

**Comment by calmilamsy** [comment]
I'm leaving them there for anyone who wants to make a patch for them.
Versions b1.6.6, b1.8.1 and b1.9-pre5 "work", but containers are broken.
Versions b1.5_01,1.5_02 and b1.4_01 are missing exceptor files.

**Comment by Dereku** [comment]
> Versions b1.5_01,1.5_02 and b1.4_01 are missing exceptor files.

Create and leave that files empty. Maybe it will work. Dunno :^)

**Comment by Johnanater** [comment]
I agree with calmilamsy if it will be worked on later.

**Comment by calmilamsy** [comment]
image
That is for b1.4_01.

Working exceptor files are **required**.

**Comment by calmilamsy** [comment]
Once this branch goes through, I plan on trying a method that will (if it works) remove the need of exceptor (its used for only 3 versions), and will make creating patches much easier.

**Comment by Johnanater** [comment]
Appears to fully function on Linux. I made a few edits and made a new class. Successfully recompiled and reobfuscated. If we could get others to confirm, I'll approve the merge. :)

**Comment by mineLdiver** [comment]
I can't use scriptsonly on a freshly downloaded lts:python3, it can't find /runtime/bin/python/python to execute setup. It gets downloaded only when I run full setup, which is wrong, like, how am I supposed to run scriptsonly without python, which gets downloaded only on a full setup?

**Comment by Johnanater** [comment]
Seems to work on Windows as well.

**Comment by Dereku** [comment]
Source files contains ``Shift-JS`` encoded comments
```
== MCP v4.3 ==
> Recompiling client...
> Gathering class list.
Traceback (most recent call last):
  File "runtime\recompile.py", line 38, in <module>
    main(options.config)
  File "runtime\recompile.py", line 23, in main
    commands.recompile(0)
  File "C:\Users\Dereku\Desktop\1.7.3-LTS-python3\runtime\commands.py", line 683, in recompile
    o = p.stdout.readline().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 8: invalid start byte```

Random error from client and that "error" again:
```
[22:19] Error in class 'CodecJOrbis'
[22:19] Unable to acquire inputstream in method 'initialize'.
[22:19] ERROR MESSAGE:
Traceback (most recent call last):
  File "runtime\startclient.py", line 25, in <module>
    main(options.config)
  File "runtime\startclient.py", line 18, in main
    commands.startclient()
  File "C:\Users\Dereku\Desktop\1.7.3-LTS-python3\runtime\commands.py", line 734, in startclient
    self.runmc(forkcmd)
  File "C:\Users\Dereku\Desktop\1.7.3-LTS-python3\runtime\commands.py", line 763, in runmc
    o = pclient.stdout.readline().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 94: invalid continuation byte```

**Comment by calmilamsy** [comment]
@Dereku 9e412ae should fix your issues.

**Comment by calmilamsy** [comment]
Should be good to merge.

Hopefully bbe9d8d and d92b1ef will fix all current issues.

**Comment by Johnanater** [comment]
Will merge :)

**Pull request merged**
