### PR TITLE
Adding fernflower

### PR DESCRIPTION
**Pull request by Dereku**
~~TODO~~:
- ~~Make diffs for other versions~~ //Too lazy to fix b1.4, need more time to do. Older versions have old csv tables, so I need to convert them to the new one.
- ~~Fix DataWatcher exception (Integer cannot be cast to Byte), throwns only with creepers~~
- ~~Remove jad~~

### CODE REVIEW

**Comment by calmilamsy** [comment]
Issue with b1.8.1 and b1.7.3. Client crashes with int cannot be cast to byte on joining server.
b1.8.1:
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
    at net.minecraft.src.DataWatcher.getWatchableObjectByte(DataWatcher.java:32)
    at net.minecraft.src.EntityCreeper.getCreeperState(EntityCreeper.java:134)
    at net.minecraft.src.EntityCreeper.onUpdate(EntityCreeper.java:47)
    at net.minecraft.src.World.updateEntityWithOptionalForce(World.java:1409)
    at net.minecraft.src.World.updateEntity(World.java:1392)
    at net.minecraft.src.World.updateEntities(World.java:1315)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1140)
    at net.minecraft.client.Minecraft.run(Minecraft.java:546)
    at java.lang.Thread.run(Unknown Source)`
b1.7.3:
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
    at net.minecraft.src.DataWatcher.getWatchableObjectByte(DataWatcher.java:32)
    at net.minecraft.src.EntityCreeper.getCreeperState(EntityCreeper.java:134)
    at net.minecraft.src.EntityCreeper.onUpdate(EntityCreeper.java:47)
    at net.minecraft.src.World.updateEntityWithOptionalForce(World.java:1305)
    at net.minecraft.src.World.updateEntity(World.java:1288)
    at net.minecraft.src.World.updateEntities(World.java:1220)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1160)
    at net.minecraft.client.Minecraft.run(Minecraft.java:539)
    at java.lang.Thread.run(Unknown Source)`

Might be safe to assume all versions have this issue.

**Comment by Dereku** [comment]
Resolved

**Comment by Dereku** [comment]
Ready to check it and merge.

**Comment by Dereku** [comment]
Guys?..

**Comment by calmilamsy** [comment]
Works fine for me.
@Johnanater should be good for merge provided it works for you too.

**Comment by Johnanater** [comment]
Sorry I'm late, but it works! Merging!

Since we already have a custom fernflower, we could also add a way to make new-line open brackets optional later on. :)

**Pull request merged**
