### PR TITLE
Preconfigured Workspace

### PR DESCRIPTION
**Pull request by calmilamsy**
Removes some of the legwork when creating a workspace. All you have to do is open /src as an eclipse workspace now.

All client libraries and natives are all preconfigured.
Both projects will appear automagically in your workspace.

Will need to be tested on different configurations first.

### CODE REVIEW

**Comment by mineLdiver** [comment]
Wait, why? There is already a workspace in the /eclipse/ folder

**Comment by calmilamsy** [comment]
> Wait, why? There is already a workspace in the /eclipse/ folder

1. They arent automatically copied.
2. They have incorrect paths.

**Comment by mineLdiver** [comment]
> 
> 
> > Wait, why? There is already a workspace in the /eclipse/ folder
> 
>     1. They arent automatically copied.
> 
>     2. They have incorrect paths.

1. Copied where?
2. Wdym incorrect paths? Works perfectly for me.

**Comment by calmilamsy** [comment]
> -snip-
> 
> 1. Copied where?
> 2. Wdym incorrect paths? Works perfectly for me.

1. Copied from `/eclipse` to `/src`
2. They refer from `/` when `/src/<project>` is the cwd, unless I am missing something.

**Comment by mineLdiver** [comment]
> 
> 
> > -snip-
> > 
> > 1. Copied where?
> > 2. Wdym incorrect paths? Works perfectly for me.
> 
>     1. Copied from `/eclipse` to `/src`
> 
>     2. They refer from `/` when `/src/<project>` is the cwd, unless I am missing something.

1. Why copying? You can just open /eclipse/ as a workspace and it'll work.
2. From above, nothing is broken if you just open /eclipse/ as workspace and not /src/

**Comment by calmilamsy** [comment]
I stand corrected.
I never knew that you could just use `/eclipse` as a workspace. Should probably edit readme to say open `/eclipse` as a workspace.

Closing.

**Comment by Johnanater** [comment]
Deleting branch...

**Comment by Dereku** [comment]
Preconfigured Workspace is a good idea. But a Eclipse's workspace - that's bad. 
If you really want to do that - look at the Maven/Gradle

**Comment by Johnanater** [comment]
Indeed

**Comment by mineLdiver** [comment]
Yep, gradle/maven for LTS would be a good addition.

**Pull request closed without merging**
