### PR TITLE
added Kotlin support

### PR DESCRIPTION
**Pull request by Jilms**
Adds Kotlin support to MCP/LTS

### CODE REVIEW

**Comment by Dereku** [comment]
Binaries size is over 8 MiB, do an optional download of the ``kotlinc``

**Comment by Johnanater** [comment]
Agreed, add an optional download in setup.sh and setup.bat.

**Comment by Johnanater** [comment]
We should probably add Kotlin support on Linux as well.

**Comment by Johnanater** [comment]
This is a mess, redo!

**Pull request closed without merging**
