### PR TITLE
Restore specialsource branch

### PR DESCRIPTION
**Pull request by Dereku**
Say "Hello" again to that PR.
Current issues: 
- None

### CODE REVIEW

**Comment by Dereku** [comment]
Oh, yes, someone, check that pr please.

**Comment by Jilms** [comment]
need to patch the TileEntity and everything else looks fine.

**Comment by Johnanater** [comment]
Just ran the decompile script and it seems to work with Windows (Wine), but has errors using the Linux scripts.

Uploading the log here:
[mcp.log-linux.zip](https://github.com/ModificationStation/1.7.3-LTS/files/3016209/mcp.log-linux.zip)

**Comment by Dereku** [comment]
Updated patches; time for test it again.

**Comment by Dereku** [comment]
I hope the SpecialSource now obfuscates all methods that declared in srg.
Test that commit - https://github.com/Dereku/1.7.3-LTS/archive/specialsource.zip

**Comment by Johnanater** [comment]
Seems to work on both Linux and Windows.

**Comment by Dereku** [comment]
This is last commit. If someone have issues/questions/improvements - welcome to the thread.

**Comment by Johnanater** [comment]
Appears to still be working, but in /src/minecraft/net/minecraft/src/ there are some classes that have ".orig" copies. Such as "Block.java.orig".

**Comment by Dereku** [comment]
Here no any issue/improvement = ready to merge.
``*.orig`` files is the work of the patching, so don't worry about that.

**Comment by Johnanater** [comment]
Looks great! I'll test out it out with some random modded jars and modding to test it more.

**Comment by Dereku** [comment]
This happened \\:D/

**Pull request merged**
